### ISSUE TITLE
Provide option to output to stdout

### ISSUE THREAD

**Issue by fungs** [klartext/any-dl#4]
Hi, I tried any-dl and I would like to integrate it into my upnp server for streaming e.g. the latest versions of Tagesschau on demand to the local network. For this, it is essential to pass the video to a pipe and not a file, which es best done by letting any-dl write to stdout instead of a file. Do you think you could implement this feature?

**Comment by fungs** [comment]
I see the construction of the download command is controlled in the parser definitions. So I guess I have to change it there everywhere... That's possible although a little inconvenient.

More importantly, if I change the system call to output to stdout, the output is still mixed with the output of any-dl which seems to write certain information to the terminal, for example

   # --------------------
   http://download.media.tagesschau.de/video/....webxl.h264.mp4
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This output should be removed if it is not controlled by the parser description or should be written to the stderr instead.

Thanks, Johannes

**Comment by klartext** [comment]
Can you give me the commands you used to invoke any-dl, and what you wanted to achieve?
Do I understand you correctly, that you want to call any-dl invoked via pipe?

any-dl was programmed with saving streams/files to a file on disk ("dl" stands for download"), but maybe writing to stdout also would make sense. 

If you will be more specific on the way you want to call any-dl, or what stuff does block you, it ould be helpful to understand your problem.

If the seperator.string  "# --------------------" is the only problem,
just invoke any-dl with  command line switch
   -sep ""

-sep stands for seperator.

The seperator is for using any-dl on command line - some typographic helper for the user's eye.

hth

**Comment by klartext** [comment]
BTW: the tagesschau-parser just invokes wget to downlkoad a mp4-file, after extracting the url of that file from tagesschau-webpages.
You talked about streaming. It looks a bit, as if you are looking for a different tool?
Otherwise, just be more specific, so I maybe can help.

**Comment by klartext** [comment]
You could also just adapt the tagesschau-parser for your needs.
It calls wget, and instead of
  paste(" wget -O ", $title, "_", $basename, " ", $mp4url );

rewrite it to let wget print to stdout.

I recommend that you copy the tagesschau-parser inside the rc-file and rename the parsername to your needs, and adapting the wget-command there.

Looks like this is the easiest way.
No need t change the any-dlsources then.

**Comment by klartext** [comment]
No answer means, one of the above mentioned suggestions work.

**Comment by fungs** [comment]
Sorry I couldn't answer earlier. What I mean is, that I call any-dl to download a video like the latest tagesschau but instead of saving it to a file it will be piped to another program which streams it over the local network. So the video is downloaded when I view it via a local media rendering client. So the video is downloaded and instantly streamed without saving it to disk. To achieve this, it must be possible to redirect the data output.

When I change the parser to call "wget -O -" and then call any-dl then the downloaded data of any-dl can't be separated from the other output text produced by any-dl. This means, that the stream is corrupted. The following text is written on the standard output which prevent the parser to be used the way I want:

./any-dl -sep "" "http://www.tagesschau.de/sendung/tagesschau/index.html"
http://download.media.tagesschau.de/video/2015/0111/TV-20150111-2022-0101.webxl.h264.mp4
"Aktuelle_Nachrichten_Inland_Ausland_Wirtschaft_Kultur_Sport_ARD_Tagesschau_tagesschau_de" 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
OUTPUT OF wget -q -O - http://download.media.tagesschau.de/video/2015/0111/TV-20150111-2022-0101.webxl.h264.mp4wget -q -O - http://download.media.tagesschau.de/video/2015/0111

Of course my application expects that the source only contains or triggers the download of a single video. I don't know how a client player would behave when to video files are concatenated in a stream.

I this now clearer?

**Comment by klartext** [comment]
Do a git pull and compile anew.

Then try this parser (add it to one of your config-files):


=====================================
parsername "fungs": ( "http://www.tagesschau.de/multimedia/video/",
                                "http://www.tagesschau.de/",
                                "http://www.tagesschau.de/multimedia/sendung/",
                                "http://www.tagesschau.de/ausland/",
                                "http://www.ardmediathek.de/das-erste/tagesthemen",
                                "http://mediathek.rbb-online.de/rbb-fernsehen/rbb-praxis/",
                                "http://www.ardmediathek.de/das-erste/tagesschau-in-100-sek",
                                "http://www.ardmediathek.de/das-erste/" )
start
  match( >>>http://(.*?).mp4<<< );
  dropcol(1);
  iselectmatch(0,"webm.h264.mp4");
  select(0);
  store("mp4url");
  basename;
  store("basename");

  # extract title
  # -------------
  recall("BASEDOC");
  titleextract;
  htmldecode;
  subst("[[:^alnum:]]+", "_");  # non-alnum -> "_"
  #print;
  store("title");

  #paste(" wget -O ", $title, "_", $basename, " ", $mp4url, " 2>/dev/null" );
  paste(" wget -O - ", $mp4url, " 2>/dev/null" );
  system;
end



=====================================

**Comment by fungs** [comment]
I tried the newest version and this seems to output no additional text on the standard output and streaming works like a charm (test by piping it into mplayer -). Thanks.

BTW: I replaced webm.h264.mp4 by webxl.h264.mp4 and set wget -q -O - instead of using 2>/dev/null
