### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fungs** [klartext/any-dl#5]
ocamlfind ocamlopt -package pcre,netstring,netsys,netclient,curl,xml-light,csv -c network.ml
File "network.ml", line 85, characters 8-28:
Error: This variant pattern is expected to have type Curl.curlCode
       The constructor CURLE_FTP_SSL_FAILED does not belong to type Curl.curlCode
Hint: Did you mean CURLE_USE_SSL_FAILED?

**Comment by fungs** [comment]
I removed the respective line and compilation succeeded...

**Comment by klartext** [comment]
Which curl version do you have installed?
I remember that I had the same (?) errmsg, until I updated to current ocaml-curl-lib.
Maybe also a "make clean" before a make would then help.
So, please let me know your lib version.

**Comment by klartext** [comment]
With OCaml version 4.02.1 and ocaml-curl 0.5.3 (which is the current version) it compiles well.
I assume you have older ocaml-curl and this creates the problem.

**Comment by fungs** [comment]
OCaml version 4.02.1
ocurl version 0.7.2 (latest installed via opam)

**Comment by klartext** [comment]
0.7.2 ??
See here, thats AFAIK the official project page, and the yhave 0.5.3 there:
  http://sourceforge.net/projects/ocurl/
Or did they change the project to a different page, so I missed newer versions?!

**Comment by fungs** [comment]
I don't know about the versions, I just used the opam manger to install the package ocurl and that's the version it gives me.
